### ISSUE TITLE
No metrics

### ISSUE THREAD

**Issue by prdev1** [oliver006/redis_exporter#167]
Dears,
I've deployed redis exporter in cloud foundry with `cf push <app_name> -f <manifest_path>`.
I guess I need to configure the list of redis hosts somewhere in the exporter app. May I know where should I configure this ? With just cf push, redis exporter doesn't scrape any metrics form the Redis VMs. 

Regards

**Comment by oliver006** [comment]
I'm not really familiar with how service discovery in CloudFoundry works but maybe @ihrigb knows more, he added Cloud Foundry support.

**Comment by ihrigb** [comment]
@prdev1
I am currently without proper internet. I will write a proper answer tomorrow.

**Comment by ihrigb** [comment]
Alright, service discovery in CF happens here: https://github.com/oliver006/redis_exporter/blob/master/exporter/discovery.go#L81
We get all bound services with tag "redis" and then read connection information from the "credentials" json object.

So you do not need to define any list of redis hosts, but just bind your redis service instances to the exporter application.

**Comment by prdev1** [comment]
@ihrigb 
I created a redis service & bound it to the redis exporter application. And then the application crashes ! 


form the logs : 

```
   2018-06-20T14:02:27.16+0200 [APP/PROC/WEB/0] ERR time="2018-06-20T12:02:27Z" level=info msg="Redis Metrics Exporter <<< filled in by build >>>    build date: <<< filled in by build >>>    sha1: <<< filled in by build >>>    Go: go1.8.7"
   2018-06-20T14:02:27.16+0200 [APP/PROC/WEB/0] ERR panic: interface conversion: interface {} is nil, not string
   2018-06-20T14:02:27.16+0200 [APP/PROC/WEB/0] ERR goroutine 1 [running]:
   2018-06-20T14:02:27.16+0200 [APP/PROC/WEB/0] ERR github.com/oliver006/redis_exporter/exporter.GetCloudFoundryRedisBindings(0x563f00000004, 0x41, 0xc42004feb0, 0x4, 0x4, 0xc420136638, 0xc42004fdc0, 0x0, 0x47084fd830fe5e3b)
   2018-06-20T14:02:27.16+0200 [APP/PROC/WEB/0] ERR 	/tmp/gobuildpack.gopath661670186/.go/src/github.com/oliver006/redis_exporter/exporter/discovery.go:89 +0x89e
   2018-06-20T14:02:27.16+0200 [APP/PROC/WEB/0] ERR main.main()
   2018-06-20T14:02:27.16+0200 [APP/PROC/WEB/0] ERR 	/tmp/gobuildpack.gopath661670186/.go/src/github.com/oliver006/redis_exporter/main.go:84 +0x2f3
```

**Comment by ihrigb** [comment]
Can you drop me your env-variables? (`cf env <app>`). Please mask URI, username and password.

**Comment by prdev1** [comment]
@ihrigb 

here it is : 


```


Getting env variables for app redis-exporter in org redid-expo / space development as <user>…
OK

System-Provided:
{
 "VCAP_SERVICES": {
  "p-redis": [
   {
    "credentials": {
     "host": “<IP>”,
     "password": “<pwd>”,
     "port": 41921
    },
    "label": "p-redis",
    "name": "redis",
    "plan": "shared-vm",
    "provider": null,
    "syslog_drain_url": null,
    "tags": [
     "pivotal",
     "redis"
    ],
    "volume_mounts": []
   }
  ]
 }
}

{
 "VCAP_APPLICATION": {
  "application_id": "6c069ed6-4468-429f-8d71-b25d04e3c50e",
  "application_name": "redis-exporter",
  "application_uris": [
   "redis-exporter.<domain>”
  ],
  "application_version": "7baff791-08c0-4202-a680-c6a453ad3eab",
  "cf_api": “<api-url>”,
  "limits": {
   "disk": 1024,
   "fds": 16384,
   "mem": 1024
  },
  "name": "redis-exporter",
  "space_id": "f28ce27c-a6d8-41df-b6b9-23a02102efe4",
  "space_name": "development",
  "uris": [
   "redis-exporter.<domain>”
  ],
  "users": null,
  "version": "7baff791-08c0-4202-a680-c6a453ad3eab"
 }
}

User-Provided:
GOPACKAGENAME: main

No running env variables have been set

Staging Environment Variable Groups:
http_proxy: http://<proxy-url>:8080
https_proxy: http://<proxy-url>:8080

```

**Comment by ihrigb** [comment]
It's indeed a bug. Current code would expect `hostname` instead of `host`. I will provide a fix.

**Comment by ihrigb** [comment]
The PR is untested as of now, I will do some testing tomorrow.

**Comment by ihrigb** [comment]
I was able to verify it on SAP CF, where it is `hostname`. @prdev1 can you please verify this on Pivotal CF?

**Comment by prdev1** [comment]
deployed new code. 

```

2018-06-21T11:05:27.014+02:00 [APP/PROC/WEB/0] [ERR] time="2018-06-21T09:05:27Z" level=info msg="Redis Metrics Exporter <<< filled in by build >>> build date: <<< filled in by build >>> sha1: <<< filled in by build >>> Go: go1.8.7"
2018-06-21T11:05:27.014+02:00 [APP/PROC/WEB/0] [ERR] time="2018-06-21T09:05:27Z" level=warning msg="Error while getting redis services no services with tag redis"
2018-06-21T11:05:27.015+02:00 [APP/PROC/WEB/0] [ERR] time="2018-06-21T09:05:27Z" level=info msg="Providing metrics at :8080/metrics"
2018-06-21T11:05:27.015+02:00 [APP/PROC/WEB/0] [ERR] time="2018-06-21T09:05:27Z" level=info msg="Connecting to redis hosts: []string(nil)"
2018-06-21T11:05:27.015+02:00 [APP/PROC/WEB/0] [ERR] time="2018-06-21T09:05:27Z" level=info msg="Using alias: []string(nil)"
```
my redis service is named as `redis` !

**Comment by ihrigb** [comment]
It does not look for the service name, but for its tags. In your case, your service has the tags "pivotal" and "redis". So actually it should find this service and take the service name "redis" as an alias.

```json
{
  "credentials": {
    "host": “<IP>”,
    "password": “<pwd>”,
    "port": 41921
  },
  "label": "p-redis",
  "name": "redis",
  "plan": "shared-vm",
  "provider": null,
  "syslog_drain_url": null,
  "tags": [
    "pivotal",
    "redis"
  ],
  "volume_mounts": []
}
```

**Comment by prdev1** [comment]
@ihrigb tell me how may I help in debugging this please

**Comment by ihrigb** [comment]
We are getting the bound redis services here: https://github.com/oliver006/redis_exporter/blob/master/exporter/discovery.go#L81
(vendor: https://github.com/oliver006/redis_exporter/blob/master/vendor/github.com/cloudfoundry-community/go-cfenv/service.go#L36).

I have no good idea, why this would fail. Maybe you can try to debug at these points.

**Comment by oliver006** [comment]
@prdev1 - I just released v0.20.0, can you try it and see if that fixes your issue?

**Comment by ihrigb** [comment]
@oliver006 any news about this?

**Comment by oliver006** [comment]
@ihrigb - thx for the follow-up. I don't have a way to test/run CloudFoundry stuff, I was hoping @prdev1 would have a chance to give this a try.

**Comment by oliver006** [comment]
Closing this, @prdev1 please re-open and provide more debug information if the issue persists.
