### ISSUE TITLE
Multiple Series Error 

### ISSUE THREAD

**Issue by penhauer-xiao** [oliver006/redis_exporter#80]
The uptime & clents & memory usage：  Can not get its value

The stack trace:

Error: Multiple Series Error
    at b.setValues (http://192.168.1.2:4001/public/app/boot.c8e57b1c.js:29:8355)
    at b.onDataReceived (http://192.168.1.2:4001/public/app/boot.c8e57b1c.js:29:6107)
    at f.emit (http://192.168.1.2:4001/public/app/boot.c8e57b1c.js:61:19286)
    at a.emit (http://192.168.1.2:4001/public/app/boot.c8e57b1c.js:61:21604)
    at b.handleQueryResult (http://192.168.1.2:4001/public/app/boot.c8e57b1c.js:55:21101)
    at i (http://192.168.1.2:4001/public/app/boot.c8e57b1c.js:51:24759)
    at http://192.168.1.2:4001/public/app/boot.c8e57b1c.js:51:25181
    at o.$eval (http://192.168.1.2:4001/public/app/boot.c8e57b1c.js:52:293)
    at o.$digest (http://192.168.1.2:4001/public/app/boot.c8e57b1c.js:51:30809)
    at o.$apply (http://192.168.1.2:4001/public/app/boot.c8e57b1c.js:52:576)

![image](https://user-images.githubusercontent.com/6280121/27380516-03d54798-56b2-11e7-8623-643c39fbf90d.png)

I found a bug about uptime when my time range was chosen to show 24 hours but my redis started just 2 minutes at this time, Uptime was N/A state and reported above the error.  May be  the clents & memory usage have been the same issue.
![image](https://user-images.githubusercontent.com/6280121/27382061-dd4f0f5e-56b7-11e7-8f35-5e76a74754bb.png)
![image](https://user-images.githubusercontent.com/6280121/27382071-ed1dbcbe-56b7-11e7-94ba-ec66e0245e1c.png)

**Comment by oliver006** [comment]
Use the promtheus UI to debug your query and find out why multiple series are returned.

If you scrape more than one redis instance then you might have to adjust the dashboard settings so that only one time series is returned for the single stat fields.
